version: '2'

services:
  hobbes-http:
    image: hobbes-http
    build: .
    network_mode: host
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./ssh:/ssh
    env_file: "docker-${HOBBES_INSTANCE_ENV}.env"
    entrypoint:
      - /bin/sh
      - -c
      - 'npm run serve'
