let roleWiseGrants = {
	'GUEST': [],
	'CADET': ['ASSIGNMENT_SELF_SUBMIT', 'EVALUATION_SELF_READ',  'EVALUATION_SELF_LIST'],
	'COMMANDER': ['ASSIGNMENT_SELF_SUBMIT', 'EVALUATION_SELF_READ', 'EVALUATION_SELF_LIST', 'EVALUATION_CADET_READ', 'VIEW_SUBMISSION_WORKFLOW_STATS']
};

module.exports = roleWiseGrants;
